version: '3'

services:
  wordpress:
    image: gregorylp/gregorylp-wordpress:latest
    ports:
      - "8080:80"
    networks:
      - frontend_network
      - backend_network
    env_file:
      - .env
    depends_on:
      - mariadb

  mariadb:
    image: gregorylp/mariadb:latest
    ports:
      - "3306:3306"
    networks:
      - backend_network
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    env_file:
      - .env

networks:
  frontend_network:
  backend_network:

volumes:
  db_data:

