version: '3'

services:
  wordpress:
    image: gregorylp/gregorylp-wordpress:latest
    ports:
      - "8080:80"
    networks:
      - frontend_network
      - backend_network
    depends_on:
      - mariadb
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: admin
      WORDPRESS_DB_NAME: projetDocker

  mariadb:
    image: mariadb:latest
    networks:
      - backend_network
    volumes:
      - ./my.cnf:/etc/mysql/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: admin

networks:
  frontend_network:
  backend_network:
