version: '3'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ES_VERSION}
    container_name: es01
    environment:
      - node.name=es01
    volumes:
      - es-data-01:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - es-net

  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ES_VERSION}
    container_name: es02
    environment:
      - node.name=es02
    volumes:
      - es-data-02:/usr/share/elasticsearch/
    ports:
      - "9201:9201"
    networks:
      - es-net

  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ES_VERSION}
    container_name: es03
    environment:
      - node.name=es03
    volumes:
      - es-data-03:/usr/share/elasticsearch/data
    ports:
      - "9202:9202"
    networks:
      - es-net

  kibana:
    image: docker.elastic.co/kibana/kibana:${ES_VERSION}
    container_name: kibana
    depends_on:
      - es01
      - es02
      - es03
    ports:
      - "5601:5601"
    networks:
      - es-net

volumes:
  es-data-01:
  es-data-02:
  es-data-03:

networks:
  es-net:
